name: release
run-name: "Release ${{ inputs.CHROMIUM_VERSION }} (chromedriver: ${{ inputs.CHROMEDRIVER_VERSION }}) for (${{ inputs.DEBIAN_VERSION }}) with push: ${{ inputs.PUSH }}"

env:
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_dispatch:
    inputs:
      CHROMEDRIVER_VERSION:
        description: "Chromedriver Version"
        required: true
        type: string
      CHROMIUM_VERSION:
        description: "Chromium Version"
        required: true
        type: string
      DEBIAN_VERSION:
        description: "Debian Version"
        required: true
        type: string
        default: 'bullseye'
      PUSH:
        description: "Push final image"
        required: true
        type: boolean
        default: false

jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: docker.pkg.github.com
      CHROMEDRIVER_VERSION: ${{ github.event.inputs.CHROMEDRIVER_VERSION }}
      CHROMIUM_VERSION: ${{ github.event.inputs.CHROMIUM_VERSION }}
      DEBIAN_VERSION: ${{ github.event.inputs.DEBIAN_VERSION }}
      LATEST: ${{ github.event.inputs.LATEST }}
      PUSH: ${{ github.event.inputs.PUSH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN || github.token }}
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_TOKEN }}

      - name: Extract simplified CHROMIUM_VERSION
        run: |
          SIMPLIFIED_VERSION=$(echo "${{ env.CHROMIUM_VERSION }}" | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
          echo "SIMPLIFIED_CHROMIUM_VERSION=$SIMPLIFIED_VERSION" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,${{ env.CHROMIUM_VERSION }}
            type=raw,${{ env.SIMPLIFIED_CHROMIUM_VERSION }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ env.PUSH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          build-args: |
            CHROMEDRIVER_VERSION=${{ env.CHROMEDRIVER_VERSION }}
            CHROMIUM_VERSION=${{ env.CHROMIUM_VERSION }}
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
